title: Richard VeselÃ½
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://richardvesely.com" # The base hostname & protocol for your sitetwitter_username: jekyllrb
robots:
  sitemap:   https://richardvesely.com/sitemap.xml
